import { Outfit, Ovo } from "next/font/google";
import "./globals.css";
import Navbar from "./_components/Navbar/Navbar";
import Header from "./_components/Header/Header";
import About from "./_components/About/About";
import Services from "./_components/Services/Services";
import Work from "./_components/Work/Work";
import Contact from "./_components/Contact/Contact";
import Footer from "./_components/Footer/Footer";

const Outfitsans = Outfit({
  subsets: ["latin"],
  weight: ["400", "500", "700", "600"],
});
const Ovosans = Ovo({
  subsets: ["latin"],
  weight: ["400"],
});

export const metadata = {
  title: "Portfoilo - GreatStack",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en" className="scroll-smooth">
      <body
        className={`${Outfitsans.className} ${Ovosans.className} antialiased leading-8 `}
      >
        <Navbar />
        <Header />
        <About />
        <Services />
        <Work />
        <Contact />
        <Footer />
        {children}
      </body>
    </html>
  );
}
